POST http://localhost:4000/api/feedback-list
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imt4bGEiLCJpZCI6IjYxYWI3ODAwNjUwYWY3ZDk4NzNjMDk4MiIsImlhdCI6MTYzODc5MjkyNCwiZXhwIjoxNjM4Nzk2NTI0fQ.MF-Kq6NbgKVDvQIPLlxd-3pkWzMnkUrY9gmVEnGcynQ

{
    "title": "Testing Feedback Tests",
    "category": "Test",
    "upvotes": 300,
    "status": "ongoing",
    "description": "This is a test for a test, with a test with jest",
    "comments": [],
     "userId": "61ab7800650af7d9873c0982"

}