POST http://localhost:4000/api/users
Content-Type: application/json

{
    "username": "rotykay",
    "name":"Korty May",
    "password": "rotykay",
    "feedback": []
}


# {
#     "username": "velvetround",
#     "name":"Zena Kelley",
#     "password": "velvetround",
#     "feedback": []
# }