POST http://localhost:4000/api/feedback-list
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvdHlrYXkiLCJpZCI6IjYxYjExZDQyOTAxNjFhZWJjODljYzJjMCIsImlhdCI6MTYzOTQ3MzA5MywiZXhwIjoxNjM5NDc2NjkzfQ.ttVsdqCaMaeXtyfXtH-9DVj8rJkcTwLBu-NDhRJNsqY

{
    "title": "Addf micro-interactions",
    "category": "enhancement",
    "upvotes": 71,
    "status": "live",
    "description": "Small anfffimations at specific points can add delight.",
    "comments": [],
    "userId": "61b11d4290161aebc89cc2c0"

}